### ISSUE TITLE
otp.retry magically throws invalid date (Date::Error)

### ISSUE THREAD

**Issue by cryshado** [ding-live/ding-ruby#3]
Hi! When I'm trying to call `otp.retry(request)` as the result it can throw `invalid date (Date::Error)` for unknown reasons, regardless of whether an error occurred, it can still deliver a retry request (i.e. I will receive a new sms). Ruby version: "3.3.5"; ding_sdk version: "0.9.11".

_ding_sdk/utils/utils.rb_ (`p("s: #{s}")` manually added for debug purposes):
<img width="809" alt="image" src="https://github.com/user-attachments/assets/52bf7b0e-1b5c-4170-a83b-6e660735ddc7">

<img width="608" alt="image" src="https://github.com/user-attachments/assets/097a4c58-aa73-4633-852d-f0a96c1e9c24">

**Comment by nerzh** [comment]
fix please 🙃
